import type { App } from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faCopy,
  faSpinner,
  faKeyboard,
  faFilter,
  faArrowUp,
  faArrowDown,
  faBell,
  faBolt,
  faCalendar,
  faCalendarDays,
  faCalendarCheck,
  faCamera,
  faChartLine,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCircleInfo,
  faComments,
  faDatabase,
  faEdit,
  faEye,
  faEyeSlash,
  faFileExcel,
  faFilePdf,
  faFileImport,
  faDownload,
  faKey,
  faLock,
  faCheck,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faPaste,
  faShield,
  faHouse,
  faLayerGroup,
  faMobile,
  faMobileScreenButton,
  faMoon,
  faPaperPlane,
  faPlus,
  faReceipt,
  faSearch,
  faShieldHeart,
  faSun,
  faTimes,
  faTrash,
  faUnlink,
  faUpload,
  faUser,
  faUserCircle,
  faWallet,
  faWifi,
} from '@fortawesome/free-solid-svg-icons'
import { faVuejs } from '@fortawesome/free-brands-svg-icons'

const icons = [
  faCopy,
  faSpinner,
  faKeyboard,
  faFilter,
  faArrowUp,
  faArrowDown,
  faBell,
  faBolt,
  faCalendar,
  faCalendarDays,
  faCalendarCheck,
  faCamera,
  faChartLine,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCircleInfo,
  faComments,
  faDatabase,
  faEdit,
  faEye,
  faEyeSlash,
  faFileExcel,
  faFilePdf,
  faFileImport,
  faDownload,
  faKey,
  faLock,
  faCheck,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faPaste,
  faShield,
  faHouse,
  faLayerGroup,
  faMobile,
  faMobileScreenButton,
  faMoon,
  faPaperPlane,
  faPlus,
  faReceipt,
  faSearch,
  faShieldHeart,
  faSun,
  faTimes,
  faTrash,
  faUnlink,
  faUpload,
  faUser,
  faUserCircle,
  faWallet,
  faWifi,
  faVuejs,
]

library.add(...icons)

export const installFontAwesome = (app: App) => {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
